title: A Geek's Page
description: Cong Wang's Personal Blog Posts
baseurl: "" # remove the /congwang.github.io
url: "https://wangcong.org" # using custom domain
github_username: congwang

# Build settings
markdown: kramdown
theme: minima
encoding: utf-8
permalink: /:year-:month-:day-:title.html
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include _pages directory
include: ['_pages']

# Force GitHub Pages to use new Jekyll version
github-pages: 232
