title: A Geek's Page
description: Cong Wang's Personal Blog Posts
baseurl: "" # remove the /congwang.github.io
url: "https://congwang.github.io" # change this to GitHub Pages URL first
github_username: congwang

# Build settings
markdown: kramdown
theme: minima
