title: A Geek's Page
description: Personal Blog Posts
baseurl: "/congwang.github.io" # if your site is in a project folder
url: "http://wangcong.org"
github_username: congwang

# Build settings
markdown: kramdown
theme: minima # or your preferred theme
