title: A Geek's Page
description: Cong Wang's Personal Blog Posts
baseurl: "" # remove the /congwang.github.io
url: "https://congwang.github.io" # change this to GitHub Pages URL first
github_username: congwang

# Build settings
markdown: kramdown
theme: minima
encoding: utf-8
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Force GitHub Pages to use new Jekyll version
github-pages: 232
